[package]
name = "wdg-request"
description = "http request"
version = "0.1.1"
authors = ["Grigoriy Baranov <baranov@w3m.co>"]
license = "MIT"
edition = "2018"

exclude = [
    ".github",
    ".gitignore",
    "README.md"
]

[dependencies]
wdg-uri = "0.1.18"
string-repr = "1.0.1"